### ISSUE TITLE
Ros Compile Error: use of deleted operator=

### ISSUE THREAD

**Issue by arthurBricq** [pvangoor/eqf_vio#6]
When running catkin_make, I was getting compilation error due to the use of deleted operator= at `eqf_vio_ros/src/eqf_vio_ros_node.cpp`, line 65 `    cbSys.featureTracker = GIFT::PointFeatureTracker(camera);`

The error comes from a new version of the GIFT library (pushed 4 days ago): commit 1338a08d8801ae22ed1d8ede6527a2f24c68b7db

This commit modifies how settings are handled, and it adds an `std::unique_ptr<Settings> settings;` into the attributes of the class. Hence it can't be copied like it is done in the ROS code. 

Quick fix: git checkout to a previous commit. 

Hope it helps anyone, 
Best

**Comment by pvangoor** [comment]
There is a bigger issue here, which is the way the ROS code tries to configure the feature tracker. I should have thought about this when I changed the GIFT interface and I will try to fix this during the week. Thanks for opening this issue!

**Comment by pvangoor** [comment]
Fixed with https://github.com/pvangoor/eqf_vio/commit/3a496c7fe3d04b39a8258d8691c08ab195832cde and https://github.com/pvangoor/GIFT/commit/a799365c0d3b72a3b9a11584ebe123b21579957d
