### ISSUE TITLE
Some problem about the accuracy.

### ISSUE THREAD

**Issue by flysoaryun** [pvangoor/eqf_vio#7]
I use ROS and run using "roslaunch eqf_vio_ros eqf_vio_ros.launch".
I test "V1_01_easy.bag" and "V2_01_easy.bag" and I use the default parameters of the program. The former data has high similarity with the trajectory of the true value only in a short time, but it is very different from the paper Figure 1, and the pose of the latter data is divergent.
Should I change some parameters?I hope I can get a reply from the author. Thank you.

**Comment by pvangoor** [comment]
Hi, the default parameters are really just a starting point, and you will need to tune it carefully to get the best performance. I would suggest looking at the feature tracking parameters especially, as they often have the biggest effect. Alternatively, please have a look at the more recent repository [eqvio](https://github.com/pvangoor/eqvio), which has many updates and upgrades over this codebase. That said, I have not yet written a ROS package for eqvio so if you require ROS you would need to write one yourself or wait a while...
