### ISSUE TITLE
googletest

### ISSUE THREAD

**Issue by woshicaijihahahaha** [pvangoor/eqf_vio#8]
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_WITH_ROS=OFF
This is being included!
/home/yy/eqf_vio/eqf_vio/libs/core/include
Building the tests.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yy/eqf_vio/eqf_vio/build/test/googletest-download
[ 11%] Performing download step (git clone) for 'googletest'
正克隆到 'googletest-src'...
fatal: 无效引用：master
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'

CMakeFiles/googletest.dir/build.make:94: recipe for target 'googletest-prefix/src/googletest-stamp/googletest-download' failed
make[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/googletest.dir/all' failed
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at test/PrepareGTest.cmake:13 (message):
  Build step for googletest failed: 2
Call Stack (most recent call first):
  test/CMakeLists.txt:3 (include)

-- Configuring incomplete, errors occurred!
See also "/home/yy/eqf_vio/eqf_vio/build/CMakeFiles/CMakeOutput.log".

**Comment by woshicaijihahahaha** [comment]
Can you help with this problem thanks

**Comment by pvangoor** [comment]
I am not sure if you meant to close it, but the issue is now fixed in 616652296f48b0702764d0c3c103a61a0dbd009b

**Comment by woshicaijihahahaha** [comment]
> I am not sure if you meant to close it, but the issue is now fixed in [6166522](https://github.com/pvangoor/eqf_vio/commit/616652296f48b0702764d0c3c103a61a0dbd009b)

Thank you very much for your help! I have solved this problem.
