### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by woshicaijihahahaha** [pvangoor/eqf_vio#9]
yy@yy:~/eqf_vio/eqf_vio/build$ make
[ 12%] Built target eqf_violib_core
[ 33%] Built target eqf_vio_lib
[ 39%] Built target eqf_vio
Scanning dependencies of target eqf_vio_gift
[ 42%] Building CXX object CMakeFiles/eqf_vio_gift.dir/src/main_gift.cpp.o
/home/yy/eqf_vio/eqf_vio/src/main_gift.cpp: In function ‘int main(int, const char**)’:
/home/yy/eqf_vio/eqf_vio/src/main_gift.cpp:130:5: error: ‘cbSys’ was not declared in this scope
     cbSys.featureTracker.settings.configure(giftConfig["GIFT"]);
     ^~~~~
/home/yy/eqf_vio/eqf_vio/src/main_gift.cpp:130:45: error: ‘giftConfig’ was not declared in this scope
     cbSys.featureTracker.settings.configure(giftConfig["GIFT"]);
                                             ^~~~~~~~~~
/home/yy/eqf_vio/eqf_vio/src/main_gift.cpp:130:45: note: suggested alternative: ‘safeConfig’
     cbSys.featureTracker.settings.configure(giftConfig["GIFT"]);
                                             ^~~~~~~~~~
                                             safeConfig
CMakeFiles/eqf_vio_gift.dir/build.make:65: recipe for target 'CMakeFiles/eqf_vio_gift.dir/src/main_gift.cpp.o' failed
make[2]: *** [CMakeFiles/eqf_vio_gift.dir/src/main_gift.cpp.o] Error 1
CMakeFiles/Makefile2:270: recipe for target 'CMakeFiles/eqf_vio_gift.dir/all' failed
make[1]: *** [CMakeFiles/eqf_vio_gift.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by woshicaijihahahaha** [comment]
Can you solve this problem? thanks.

**Comment by pvangoor** [comment]
Hi, I accidentally introduced this problem in 3a496c7fe3d04b39a8258d8691c08ab195832cde
I have fixed it in 0b1334ec868dfaabc57f97371c21abd1fe2d5b63

**Comment by woshicaijihahahaha** [comment]
Thank you for your help, you are awesome.
